<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'category_id',
        'name',
        'price',
        'cost_price',
        'description',
        'is_available',
        'stock_quantity',
    ];

    protected $casts = [
        'price' => 'decimal:2',
        'cost_price' => 'decimal:2',
        'is_available' => 'boolean',
    ];

    /**
     * Get the category that owns this product
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Get all sales items for this product
     */
    public function salesItems(): HasMany
    {
        return $this->hasMany(DailySalesItem::class);
    }

    /**
     * Get all branch stocks for this product
     */
    public function branchStocks(): HasMany
    {
        return $this->hasMany(BranchStock::class);
    }

    /**
     * Get total quantity sold for this product
     * @param int|null $branchId Optional branch ID to filter by
     */
    public function getTotalSold($branchId = null)
    {
        $query = $this->salesItems();
        
        if ($branchId) {
            $query->whereHas('sale', function ($q) use ($branchId) {
                $q->where('branch_id', $branchId);
            });
        }
        
        return $query->sum('quantity');
    }

    /**
     * Get total revenue generated by this product
     * @param int|null $branchId Optional branch ID to filter by
     */
    public function getTotalRevenue($branchId = null)
    {
        $query = $this->salesItems();
        
        if ($branchId) {
            $query->whereHas('sale', function ($q) use ($branchId) {
                $q->where('branch_id', $branchId);
            });
        }
        
        return $query->sum('total');
    }

    /**
     * Scope to get only available products
     */
    public function scopeAvailable($query)
    {
        return $query->where('is_available', true);
    }

    /**
     * Scope to get products by category
     */
    public function scopeByCategory($query, $categoryId)
    {
        return $query->where('category_id', $categoryId);
    }

    /**
     * Check if product is available
     */
    public function isAvailable(): bool
    {
        return $this->is_available;
    }

    /**
     * Get profit margin per unit
     */
    public function getProfitMargin(): float
    {
        return $this->price - $this->cost_price;
    }

    /**
     * Get profit margin percentage
     */
    public function getProfitMarginPercentage(): float
    {
        if ($this->cost_price <= 0) {
            return 0;
        }
        return (($this->price - $this->cost_price) / $this->cost_price) * 100;
    }

    /**
     * Get total profit generated by this product
     * @param int|null $branchId Optional branch ID to filter by
     */
    public function getTotalProfit($branchId = null)
    {
        $totalSold = $this->getTotalSold($branchId);
        return $totalSold * $this->getProfitMargin();
    }

    /**
     * Get total cost of goods sold for this product
     * @param int|null $branchId Optional branch ID to filter by
     */
    public function getTotalCost($branchId = null)
    {
        $totalSold = $this->getTotalSold($branchId);
        return $totalSold * $this->cost_price;
    }
}