<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'category_id',
        'name',
        'price',
        'description',
        'is_available',
    ];

    protected $casts = [
        'price' => 'decimal:2',
        'is_available' => 'boolean',
    ];

    /**
     * Get the category that owns this product
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Get all sales items for this product
     */
    public function salesItems(): HasMany
    {
        return $this->hasMany(DailySalesItem::class);
    }

    /**
     * Get total quantity sold for this product
     */
    public function getTotalSold()
    {
        return $this->salesItems()->sum('quantity');
    }

    /**
     * Get total revenue generated by this product
     */
    public function getTotalRevenue()
    {
        return $this->salesItems()->sum('total');
    }

    /**
     * Scope to get only available products
     */
    public function scopeAvailable($query)
    {
        return $query->where('is_available', true);
    }

    /**
     * Scope to get products by category
     */
    public function scopeByCategory($query, $categoryId)
    {
        return $query->where('category_id', $categoryId);
    }

    /**
     * Check if product is available
     */
    public function isAvailable(): bool
    {
        return $this->is_available;
    }
}